server:
  port: 8185
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service:8183/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
      - id: elastic-query-service-1
        host: localhost
        port: 8186
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client-2'
            client-secret: '{cipher}30b7fa6d963e69b4bc9f20f5fe9b0c30c1f90e6931dd9d3a76905b5e12882a4c00a607eb37f6552484f61ed30f5b490a7e7664526a24a5ba2dfaf51f9c080955'
            authorization-grant-type: authorization_code
            redirect-uri: http://elastic-query-web-client-2:8185/elastic-query-web-client/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            issuerUri: http://keycloak-authorization-server:9091/auth/realms/microservices-realm
security:
  logout-success-url: http://elastic-query-web-client-2 :8185/elastic-query-web-client
  default-client-registration-id: keycloak

user-config:
  username: test
  password: ENC(zON9u7s3ED6OuJ7WLug8SfBiPBJrOFEmvrdyBRZZbAUX7LScGQMIppJvfoVkW5lC)
  roles: USER