server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service:8183/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
      - id: elastic-query-service-2
        host: localhost
        port: 8185
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            #client-secret: '{cipher}bef99ccb16b9e2dc11ee71430c40b89f1cce02a5ba748ad8f39e894ebbbc6834cc0b7432d4aeb3e1af616a630fe3c21f704c65db6a227bc3d11c47fd7202689e'
            client-secret: 641525d3-dfdc-41ad-ad2b-2ef0c585489f
            authorization-grant-type: authorization_code
            redirect-uri: http://elastic-query-web-client-1:8184/elastic-query-web-client/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            issuerUri: http://keycloak-authorization-server:9091/auth/realms/microservices-realm
security:
  logout-success-url: http://elastic-query-web-client-1:8184/elastic-query-web-client
  default-client-registration-id: keycloak

user-config:
  username: test
  password: '{cipher}a190910667126ac6aa3594a19b1738f85a8d9c6243496b44f7ed48448ff0535d'
  roles: USER